### ISSUE TITLE
Include feat_lvl1/2_to_afni.R Scripts in Package

### ISSUE THREAD

**Issue by wasciutto** [UNCDEPENdLab/fmri.pipeline#12]
There are some scripts in `inst/Rscript` that look like they may be includable in the package?

I'm especially interested in getting feat_lvl1/2_to_afni.R in there because of a request I've had to view these levels with AFNI.

When I tried to run them though, their "run afni command" logic seemed to not have been updated to how it is currently used.

**Comment by michaelhallquist** [comment]
Good idea! I cleaned up these scripts a bit and made them portable as part of the package installation in 81fe67e. You can access them from their installed location using `system.file`, like `system.file("Rscript/feat_lvl1_to_afni.R", package = "fmri.pipeline")`
